decode – fLDPC
decode Subroutine
30 statements
Source File
public subroutine decode(this, llr_channel, llr_updated, synd, N_iterations)
Iteratively decode array of LLR (or LAPPRs) based on syndrome
Type Bound
TDecoder
Arguments
Type Intent Optional Attributes Name
class(TDecoder) :: this
Decoder
real(kind=wp), intent(in) :: llr_channel(this%vnum)
Array of LLRs (or LAPPRs) obtained from the channel
real(kind=wp), intent(out) :: llr_updated(this%vnum)
Array of processed LLRs (or LAPPRs)
logical, intent(in) :: synd(this%cnum)
Syndrome
integer, intent(inout) :: N_iterations
Maximum number of iterations (in), actual number of iterations (out)
Calls
Call graph
decode calls check_llr, process_cnode, process_vnode
process_cnode calls process_xnode
process_vnode calls process_xnode