TDecoder – fLDPC
TDecoder Interface
3 statements
Source File
public interface TDecoder
Calls
Module Procedures
public function TDecoderConstructor(N, e_to_v, e_to_c) result(decoder)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: N
Number of edges
integer, intent(in) :: e_to_v(N)
each location contains the index of the variable node connected to the edge corresponding to that location
integer, intent(in) :: e_to_c(N)
each location contains the index of the check node connected to the edge corresponding to that location
Return Value type(TDecoder)
The resulting Decoder object
Call graph
tdecoder calls tdecoderconstructor
tdecoderconstructor calls edge_to_node_convert_table, invert_table